version: "3.1"
services:
  app:
    build:
      context: "." 
      dockerfile: "./Dockerfile" 
    depends_on:
      - primary-db
    links :
      - primary-db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres@primary-db/motorola
      NODE_ENV: production
  primary-db:
    image: postgres:9.6.2-alpine 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: motorola 
